spring:
  application:
    name: model-service
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
#   springdoc.show-actuator=tru
      max-request-size:
        100MB
      max-file-size:
        100MB
#  cache:
#    type: redis
#    redis:
#      time-to-live: 60000
#  data:
#    redis:
#      host: localhost
#      port: 6379
#   sprg.servlet.multipart.max-file-size=50MB
#   spring.servlet.multipart.max-request-size=50MB
model:
   id : 52
#springdoc:
#  show-actuator: true